// <auto-generated />
using hardcover_form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace hardcoverform.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20180525112648_FieldsOverhaul")]
    partial class FieldsOverhaul
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hardcover_form.Models.SalesForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AantalPaginasBinnenwerk");

                    b.Property<string>("Adres");

                    b.Property<bool>("AfleveradresBekend");

                    b.Property<bool>("AfwijkendeBindwijze");

                    b.Property<bool>("AmerikaansStofwikkel");

                    b.Property<bool>("Banderol");

                    b.Property<string>("Bedrijfsnaam");

                    b.Property<bool>("BedrukkingAlloverDispersielak");

                    b.Property<bool>("BedrukkingAndersZieToelichting");

                    b.Property<string>("BedrukkingBinnenwerk");

                    b.Property<bool>("BedrukkingBlinddruk");

                    b.Property<bool>("BedrukkingFoliedruk");

                    b.Property<bool>("BedrukkingGlansLaminaat");

                    b.Property<bool>("BedrukkingKrasvastMatLaminaat");

                    b.Property<bool>("BedrukkingMatLaminaat");

                    b.Property<string>("BedrukkingSchutbladen");

                    b.Property<bool>("BedrukkingSpotUV");

                    b.Property<string>("BedrukkingStofwikkel");

                    b.Property<bool>("BedrukkingZeefdruk");

                    b.Property<bool>("CertifiedPDFs");

                    b.Property<string>("Contactpersoon");

                    b.Property<string>("DatumDoorsturen");

                    b.Property<bool>("DrukproefOpOplagepapier");

                    b.Property<string>("Emailadres");

                    b.Property<string>("FormaatBoekblokGesloten");

                    b.Property<string>("FormaatOpen");

                    b.Property<bool>("FransStofwikkel");

                    b.Property<bool>("Gequillotineerd");

                    b.Property<bool>("HalflinnenBand");

                    b.Property<bool>("HandzameDubbelgolfkartonnenDozen");

                    b.Property<string>("Herdruk");

                    b.Property<bool>("IndividueelOnderKrimpfolie");

                    b.Property<bool>("InkjetKleurproef");

                    b.Property<bool>("Kapitaalbandje");

                    b.Property<string>("Klant");

                    b.Property<bool>("Leeslintje");

                    b.Property<bool>("LinnenBand");

                    b.Property<bool>("MinOversteekPlatten");

                    b.Property<string>("Offertenummer");

                    b.Property<bool>("OmzettingAfbeeldingProfiel");

                    b.Property<bool>("OpenBestanden");

                    b.Property<string>("Oplage");

                    b.Property<string>("PapierBand");

                    b.Property<string>("PapierBinnenwerk");

                    b.Property<string>("PapierDiktePlatten");

                    b.Property<string>("PapierSchutbladen");

                    b.Property<string>("PapierStofwikkel");

                    b.Property<bool>("PapierenBand");

                    b.Property<string>("PlanningGekend");

                    b.Property<string>("PrijsCommercieelOverleggen");

                    b.Property<bool>("RechteRugInleg");

                    b.Property<bool>("RechteRugVanRol");

                    b.Property<bool>("RondeRug");

                    b.Property<bool>("Taalwissels");

                    b.Property<bool>("TariefBeeldbewerkingPerUur");

                    b.Property<string>("Telefoon");

                    b.Property<string>("Toelichting");

                    b.Property<string>("Voorbespreken");

                    b.Property<string>("Werktitel");

                    b.HasKey("ID");

                    b.ToTable("SalesForms");
                });
#pragma warning restore 612, 618
        }
    }
}
