// <auto-generated />
using hardcover_form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace hardcoverform.Migrations
{
    [DbContext(typeof(SalesContext))]
    partial class SalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hardcover_form.Models.SalesForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aanvullend");

                    b.Property<bool>("AfwijkendeBindwijze");

                    b.Property<bool>("AllOverDispersielak");

                    b.Property<bool>("AmerikaansStofwikkel");

                    b.Property<bool>("AndersZieAanvullend");

                    b.Property<string>("Band");

                    b.Property<bool>("BanderolBuikband");

                    b.Property<string>("Bandmateriaal");

                    b.Property<string>("Bedrijfsnaam");

                    b.Property<string>("Binnenwerk");

                    b.Property<bool>("Blinddruk");

                    b.Property<string>("Contactpersoon");

                    b.Property<string>("DatumDoorsturen");

                    b.Property<string>("Dikte");

                    b.Property<bool>("EenheidsprijsDigitaal");

                    b.Property<bool>("EenheidsprijsDrukproef");

                    b.Property<bool>("EenheidsprijsRgbCmyk");

                    b.Property<string>("Emailadres");

                    b.Property<bool>("Foliedruk");

                    b.Property<string>("FormaatBoekblokGesloten");

                    b.Property<string>("FormaatOpen");

                    b.Property<bool>("FransStofwikkel");

                    b.Property<bool>("Gequillotineerd");

                    b.Property<bool>("GlansLaminaat");

                    b.Property<bool>("HalflinnenBand");

                    b.Property<bool>("IndividueelKrimpfolie");

                    b.Property<bool>("Integraalband");

                    b.Property<bool>("Kapitaalbandje");

                    b.Property<bool>("KrasvastMatLami");

                    b.Property<bool>("Leeslintje");

                    b.Property<bool>("LinnenBand");

                    b.Property<bool>("MatLaminaat");

                    b.Property<bool>("MinOversteekPlatten");

                    b.Property<string>("Oplage");

                    b.Property<string>("PapierBinnenwerk");

                    b.Property<string>("PapierSchutbladen");

                    b.Property<string>("PapierStofwikkel");

                    b.Property<bool>("PapierenBand");

                    b.Property<string>("Postadres");

                    b.Property<bool>("RechteRug");

                    b.Property<bool>("RechteRugRol");

                    b.Property<bool>("RondeRug");

                    b.Property<string>("Schutbladen");

                    b.Property<bool>("SpotUv");

                    b.Property<bool>("Standaard");

                    b.Property<string>("Stofwikkel");

                    b.Property<bool>("Taalwissels");

                    b.Property<string>("Werktitel");

                    b.HasKey("ID");

                    b.ToTable("SalesForms");
                });
#pragma warning restore 612, 618
        }
    }
}
